Bin file tests
angelolab/mibi-bin-tools pull request #13
Opened 2022-01-12 00:57 UTC by ackagel

adds testing framework to bin file tools

2022-01-12 01:23 UTC, ackagel commented
does anything special need to happen for coveralls to work here?

2022-01-12 02:29 UTC, ngreenwald requested changes
Looks good. I turned on coveralls, should trigger on the next build

2022-01-12 02:29 UTC, ngreenwald commented on test-requirements.txt
> +pytest-asyncio>=0.15.1
Let's name this requirements-test instead of test-requirements to be consistent with ark, also ensures they show up next to each other when listed alphabetically.

2022-01-12 02:29 UTC, ngreenwald commented on tests/bin_files_test.py
> +    @parametrize(('do_all_intensities',), (True, False))
What does this do?

2022-01-12 02:29 UTC, ngreenwald commented on tests/bin_files_test.py
> +    suffix_names = [
Nice, this makes for a very elegant test (even though it doesn't use the fancy new functions above yet)

2022-01-12 02:29 UTC, ngreenwald commented on tests/bin_files_test.py
> +    with open(os.path.join(folder, name), 'w'):
This works?? Cool

2022-01-12 02:29 UTC, ngreenwald commented on tests/bin_files_test.py
> +@parametrize_with_cases('panel', cases=FovMetadataTestPanels, glob='*_success')
The glob here is a substring to identify the cases that are expected are to succeed?

2022-01-12 02:29 UTC, ngreenwald commented on tests/bin_files_test.py
> +# TODO: get reasonable sized test data for this
Remind me tomorrow and I'll make one

2022-01-12 02:29 UTC, ngreenwald commented on tests/bin_files_test.py
> +    bin_files._fill_fov_metadata(TEST_DATA_DIR, fov, panel, intensities, time_res, channels)
So this is essentially a triple nested for loop that will iterate overall all combinations of the input parameters?

2022-01-12 03:36 UTC, ackagel commented on tests/bin_files_test.py
> +    @parametrize(('do_all_intensities',), (True, False))
essentially creates two 'global intensities' cases, once where `intensities=True` and one where `intensities=False`.  Technically I could've also put the `['HH3']` case in there, but I felt that case deserved some separation.

2022-01-12 04:01 UTC, ackagel commented on tests/bin_files_test.py
> +@parametrize_with_cases('panel', cases=FovMetadataTestPanels, glob='*_success')
yeah, any `case_*_success()` method in the given class.  The failure cases aren't complete (probably won't be in this PR) but they'd be templated like:

```
class TestCases:
    def case_something_failure():
        return some_arg, error_type, error_msg

@parametrize_with_cases('some_arg, error_type, err_msg', cases=TestCases, glob='*_failure')
def test_something_fails(some_arg, error_type, err_msg):
    with pytest.raises(error_type, err_msg):
        something(some_arg)
```

2022-01-12 04:20 UTC, ackagel commented on tests/bin_files_test.py
> +    bin_files._fill_fov_metadata(TEST_DATA_DIR, fov, panel, intensities, time_res, channels)
it's a triple nested for loop ✨  _with style_ ✨ 

but in combination with fixtures, these decorators can also validate return values, error types, and error messages.  learning to use them that way will take a few hours, which means (to me) that functionality will be incorporated in a different PR.

2022-01-12 04:31 UTC, ngreenwald commented on tests/bin_files_test.py
> +    bin_files._fill_fov_metadata(TEST_DATA_DIR, fov, panel, intensities, time_res, channels)
yup, sounds good

2022-01-13 04:01 UTC, ngreenwald approved these changes
Looks good

2022-01-13 19:41 UTC, merged