Bug 10 fix intensity argument
angelolab/mibi-bin-tools pull request #16
Opened 2022-01-14 18:28 UTC by ackagel

closes issue #10

2022-01-14 18:31 UTC, ackagel commented on tests/bin_files_test.py
> +                any(intensities if hasattr(intensities, '__iter__') else [intensities])
I use this logic here multiple times, you think this should be a small utility function?

2022-01-14 19:21 UTC, alex-l-kong reviewed
Looks good, just a few comments.

2022-01-14 19:21 UTC, alex-l-kong commented on tests/bin_files_test.py
> +                any(intensities if hasattr(intensities, '__iter__') else [intensities])
I'd say yes, looks just a bit cleaner.

2022-01-14 19:21 UTC, alex-l-kong commented on mibi_bin_tools/bin_files.py
>          fov['intensities'] = fov['targets']
This looks good, just curious if `'intensities'` needs to be assigned as a key to `fov`? It looks like this key is just a helper to defining `'calc_intensity'`.

2022-01-14 20:06 UTC, ackagel commented on mibi_bin_tools/bin_files.py
>          fov['intensities'] = fov['targets']
good point; I'll double check I don't call it anywhere else.  At some point, I might pivot from using a dictionary to using a dataclass for fov metadata.  Easier to document fields there than in a dictionary

2022-01-15 00:48 UTC, alex-l-kong reviewed
Looks good to me.

2022-01-15 04:15 UTC, ngreenwald requested changes
Looks nice overall

2022-01-15 04:15 UTC, ngreenwald commented on tests/bin_files_test.py
> +    def filepath_checks(out_dir, fov_name, targets, intensities):
I like this function, nice compact way to check outputs. What is the rationale behind returning it within the `_write_outs` function, and calling `_write_outs` in the tests below, rather than just using this in the test?

2022-01-15 05:00 UTC, ackagel commented on tests/bin_files_test.py
> +    def filepath_checks(out_dir, fov_name, targets, intensities):
mostly vestigial from messing around with fixtures.

that being said, it's kind of nice to be able to see which tests use `_write_outs` just by looking at the function args.  definitely one of those situations where it's easier to read **_if_** you've taken the few minutes to learn about fixtures, otherwise it could look like confusing syntax sugar.

i'm fine leaving it as is, or unwrapping `filepath_checks`

2022-01-15 06:58 UTC, ngreenwald commented on tests/bin_files_test.py
> +    def filepath_checks(out_dir, fov_name, targets, intensities):
"it's kind of nice to be able to see which tests use _write_outs just by looking at the function args." 
I'm not following this point

2022-01-15 08:54 UTC, ackagel commented on tests/bin_files_test.py
> +    def filepath_checks(out_dir, fov_name, targets, intensities):
so each one of the proper test functions can basically take this form:

```
@parametrize_with_cases('param1', ...)
...
@parametrize_with_cases('paramN', ...)
def test_something(param1, ..., paramN, fixture1, ..., fixtureM):
    ...
```

Because of the fixtures, I can read exactly what it's going to check the case results against just by reading the function arguments.  Without the fixtures, I'd need to peruse through the function body to find what it's checking the cases against, if anything.

not saying it's necessary, and I'm not sure if it scales well for many fixtures or cases, but that's the plus side in terms of readability to power users (users being test writers I suppose).

2022-01-18 21:57 UTC, ackagel commented on tests/bin_files_test.py
> +    def filepath_checks(out_dir, fov_name, targets, intensities):
change name of write outs to `filepath_check` (or something)

2022-01-20 00:38 UTC, ngreenwald approved these changes

2022-01-20 00:38 UTC, merged