Adds total count extraction
angelolab/mibi-bin-tools pull request #18
Opened 2022-01-20 19:36 UTC by ackagel

closes issue #12

2022-01-21 16:48 UTC, ngreenwald commented on mibi_bin_tools/_extract_bin.pyx
> +cdef MAXINDEX_t _extract_total_counts(const char* filename):
Docstring please

2022-01-21 16:51 UTC, ngreenwald commented on mibi_bin_tools/bin_files.py
> +    """
Add Return def

2022-01-21 16:53 UTC, ngreenwald commented on tests/bin_files_test.py
> +def test_get_total_counts():
Can we check that the result is the same as extracting a given channel from a mass range of 0 to 250 or something? I can get you a smaller binfile, or a couple different smaller binfiles, so we can add some correctness checks.

2022-01-21 18:26 UTC, alex-l-kong reviewed
Nothing else to add from me. This takes me back to my early days in Davis working with C.

2022-01-22 00:09 UTC, ackagel commented on tests/bin_files_test.py
> +def test_get_total_counts():
sure sure

2022-01-22 00:10 UTC, ackagel commented on tests/bin_files_test.py
> +def test_get_total_counts():
at some-point, we make some fake bin file generating code that have the relevant structures we're checking against.  Then the bin files can be as small as we need for testing

2022-01-22 00:44 UTC, ngreenwald commented on tests/bin_files_test.py
> +def test_get_total_counts():
For sure. Which types do you want? Moly FOVs, non FOVs?

I was thinking it would be useful to have some from two different detector voltages so we know the MPH will be higher in one

2022-01-28 02:09 UTC, ngreenwald requested changes
Looks good, just a few questions

2022-01-28 02:09 UTC, ngreenwald commented on tests/bin_files_test.py
> +def test_fill_fov_metadata_failure(test_dir, fov, panel, err, channels, intensities):
One thing that's confusing about re-using Classes to be parametrized across different functions is that it makes it harder to follow the logic of why certain cases were included, and others weren't. There's a obviously a tradeoff between just copying the same code over, but right now I'm looking at the `test_fill_fov_metadata_failure` function, and seeing a bunch of globs for 'success' that are getting parametrized. The reason I assume is because the `err` message won't work across all functions, since it'll get caught at different spots. However, it starts to detract from the benefit of having an easy decorator to describe what is being tested.

2022-01-28 02:09 UTC, ngreenwald commented on tests/bin_files_test.py
> +    bin_files._fill_fov_metadata(test_dir, fov, panel, intensities, time_res, channels)
Do we need the `pass` on line 178?

2022-01-28 02:09 UTC, ngreenwald commented on tests/bin_files_test.py
> +        return ['SMA']
I don't think the failure case is used for this function. Can any of these be converted to `xfail` directly on the case, and therefore avoid the need to glob specific cases within the test function?

2022-01-28 20:22 UTC, ackagel commented on tests/bin_files_test.py
> +    bin_files._fill_fov_metadata(test_dir, fov, panel, intensities, time_res, channels)
nope

2022-01-28 21:17 UTC, ackagel commented on tests/bin_files_test.py
> +def test_fill_fov_metadata_failure(test_dir, fov, panel, err, channels, intensities):
agreed.  I consolidated the combinations that fail into another class for now.  There's some redundancies in call signature, and there's probably a better way to flag these failing case-combinations, but the version I just pushed seems legible for now

2022-01-28 21:18 UTC, ackagel commented on tests/bin_files_test.py
> +        return ['SMA']
apparently these don't actually cause a failure since these are optional filter parameters.  It'd probably be best if unfound filters raised warnings but that seems like 'bonus polish'.

2022-01-28 22:10 UTC, ngreenwald approved these changes

2022-02-08 20:53 UTC, merged