adds xarray return option to _extract_bin_files
angelolab/mibi-bin-tools pull request #23
Opened 2022-02-15 02:29 UTC by ackagel

closes issue #20 

direct ndarray return would've been a little awkward with 5 dimensions (fov, pulse/intensity/area, x, y, channel), so I settled for an xarray return.

2022-02-15 02:31 UTC, ackagel commented
@ngreenwald lmk if you want me to expand on the testing at all.  for now, I'm just making sure that the correct dimension names are returned.  If we want to check for full correctness (as in file writes match direct returns) then I can move those calls into the tempfile context and check in there.  That felt a little overkill, but I can totally implement that if you think it's worth it.

2022-02-15 06:37 UTC, ngreenwald requested changes
Just a small addition. Can you also update the make panels function, either in here or a separate PR?

2022-02-15 06:37 UTC, ngreenwald commented on tests/bin_files_test.py
> +    assert(list(test_xr.dims) == ['fov', 'type', 'x', 'y', 'channel'])
I don't think an exact correctness test is necessary, but adding a check that the number of FOVs is what's expected and that the different FOVs aren't identical should be enough to ensure that the concat logic is working

2022-02-15 21:00 UTC, ackagel commented on tests/bin_files_test.py
> +    assert(list(test_xr.dims) == ['fov', 'type', 'x', 'y', 'channel'])
right now, I'm only testing `extract_bin_files` on one fov (one moly and one tissue).  If you have another small tissue or moly fov from the same run, I could add that to the testing data to cover that case.  I could also just merge copies of the tissue+moly into one run, but I'm not 100% sure they'll play nice, before trying it.

2022-02-15 21:04 UTC, ngreenwald commented on tests/bin_files_test.py
> +    assert(list(test_xr.dims) == ['fov', 'type', 'x', 'y', 'channel'])
Yeah, the tiny_bin_files folder I sent you has three FOVs in it

2022-02-16 23:01 UTC, ngreenwald approved these changes
Looks good

2022-02-17 01:05 UTC, merged