Extract intensities
angelolab/mibi-bin-tools pull request #38
Opened 2022-07-05 19:28 UTC by camisowers

**If you haven't already, please read through our [contributing guidelines](https://ark-analysis.readthedocs.io/en/latest/_rtd/contributing.html) before opening your PR**

**What is the purpose of this PR?**

Closes #37 

**Remaining issues**

If there are specific areas of your implementation that you feel need specific feedback, or if there are things you aren't sure about, please highlight them here

2022-07-05 20:00 UTC, ngreenwald requested changes
Looks good. However, now that the logic is more complex, the testing is going to be more complex as well.

2022-07-05 20:00 UTC, ngreenwald commented on mibi_bin_tools/bin_files.py
> +        if i+1 > img_data.shape[0]:
Here and below as well

2022-07-05 20:00 UTC, ngreenwald commented on mibi_bin_tools/bin_files.py
> +                intensities = fov['targets']
Here as well

2022-07-05 20:00 UTC, ngreenwald commented on tests/bin_files_test.py
> +        # correct write out without intensities
Now that we're substituting one file type (intensity image) for another (pulse count), it's not enough to just check that the file is created in the right place. We also need to make sure that the right file is actually being saved. I would recommend mocking `_extract_bin.c_extract_bin` to return an array with known values at each index. Then, you can check to make sure the right data is being saved to the right spot

2022-07-05 20:00 UTC, ngreenwald commented on tests/bin_files_test.py
> +        # correct write out without intensities
Now that I've written all of that out, it probably makes sense to factor our the dimensionality merging code into a helper function. That way the correctness checks can happen just on that function

2022-07-05 20:10 UTC, camisowers commented on tests/bin_files_test.py
> +        # correct write out without intensities
sounds good

2022-07-06 21:10 UTC, ngreenwald approved these changes
Looks good! We'll need a new tag/release so that we can bump the import in toffy

2022-07-06 21:10 UTC, merged