Parallelize histogram and MPH calculations
angelolab/mibi-bin-tools pull request #63
Opened 2023-09-26 23:52 UTC by alex-l-kong

**What is the purpose of this PR?**

Closes #58. Closes #62. Optimizes extraction of histograms needed for median pulse height calculations by doing it in parallel.

**How did you implement your changes**

Modifies:

- `bin_files.get_histograms_per_tof`
- `bin_files.get_median_pulse_height`
- `_extract_bin.c_extract_histograms`
- `_extract_bin.extract_histograms`

The functions in `bin_files.py` now take a list of channels (or `None` to extract data for all channels). This then propagates over to `c_extract_histograms` so the underlying loops only need to run once (previously, they ran multiple times for each channel, needlessly increasing the complexity by a factor of num_channels_to_extract).

**Remaining issues**

We'll need to keep `toffy` pinned at `0.2.10` for the time-being, since this introduces breaking changes. A separate PR will update `toffy` to be compatible with the new median pulse height calculation process.

2023-09-27 17:28 UTC, srivarra requested changes
Looks good, just a suggestion for an additional test.

2023-09-27 17:28 UTC, srivarra commented on tests/bin_files_test.py
> +        ['SMA'],
Can we add a test for multiple channels selected?

2023-09-28 00:46 UTC, srivarra approved these changes
Looks good!

2023-09-29 21:31 UTC, ngreenwald requested changes
Did you confirm output is the same with this version and previous version for real data?

2023-09-29 21:32 UTC, ngreenwald commented
Maybe first leave the old, incorrect logic for corner cases intact, and make sure the parallelization doesn't change anything. Once you've confirmed that, see how big of a difference switching the logic makes across some real data

2023-10-02 18:05 UTC, alex-l-kong commented
@ngreenwald already been testing on some SPAIN cohort FOVs, confirmed that the outputs (widths, intensities, pulse_counts, and median pulse heights) match up for all of them. Optimization provides a 5-7x speed increase.

2023-10-02 19:08 UTC, camisowers approved these changes
Code looks good to me.

2023-10-02 21:13 UTC, alex-l-kong commented
> Okay got it. And how significantly do the outputs change with the fixed logic?

With the updated `_minimum_larger_value_in_sorted`, only around 0.05% of pixels are affected (makes sense, since #62 would only apply to a small subset of pixels). However, of those affected, their intensities change dramatically, up to a thousand or even 5000 or higher in some cases.

2023-10-02 21:51 UTC, ngreenwald commented
Okay, so the overall MPH of a given image doesn't change appreciably?

2023-10-02 21:58 UTC, alex-l-kong commented
> Okay, so the overall MPH of a given image doesn't change appreciably?

Barely any changes at all, single digit differences at most.

2023-10-02 22:04 UTC, ngreenwald approved these changes

2023-10-02 22:05 UTC, merged